global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:9000']

  - job_name: 'etudiant-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['etudiant-service:8080']
        labels:
          application: "Etudiant Service"

  - job_name: 'travail-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['travail-service:8081']
        labels:
          application: "Travail Service"

  - job_name: 'groupe-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['groupe-service:8082']
        labels:
          application: "Groupe Service"
